<a href="https://colab.research.google.com/github/jennadof/assignment/blob/main/Kagconversionproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Kag Conversion Project

In [ ]:
#importing Libraries
import numpy as np



In [ ]:
data_file = "/content/KAG_Conversion_Data.csv"
data_str = np.genfromtxt(data_file, delimiter=",", skip_header=1,dtype=str)
data_float = np.genfromtxt(data_file, delimiter=",",skip_header=1,dtype=float)
# printing the data

print("\nData: \n\n", data_str)


Data: 

 [['708746' '916' '103916' ... '1.429999948' '2' '1']
 ['708749' '916' '103917' ... '1.820000023' '2' '0']
 ['708771' '916' '103920' ... '0' '1' '0']
 ...
 ['1314412' '1178' '179979' ... '40.28999949' '2' '0']
 ['1314414' '1178' '179981' ... '198.7100005' '8' '2']
 ['1314415' '1178' '179982' ... '165.6099987' '5' '2']]


In [ ]:
data_float

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [ ]:
#how many unique ad campaigns(xyzcampaignid) does this data contain?
#and for how many times was eacg campaign run?
xyz_campaign_id = data_str[:,1]
print(xyz_campaign_id)
ad_id = len(xyz_campaign_id)
print(ad_id)


['916' '916' '916' ... '1178' '1178' '1178']
1143


In [ ]:
#what are the age groups that were targeted through these as campaign?
age_group = data_str[:,3]
print(age_group)


['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


In [ ]:
#what was the average, minimum and maximum amount spent on the ads?
amount_spent = data_float[:,8]
print(amount_spent)
min_spent = np.min(amount_spent)
print(min_spent)
max_spent = max(amount_spent)
print(max_spent)
ave_spent = np.average(amount_spent)
print(amount_spent)

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]
0.0
639.9499981
[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]


In [ ]:
ad_id = data_float[:,0]
print(ad_id)
clicks = max(ad_id)
print(clicks)




[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]
1314415.0


In [ ]:
#what is the id of the ad having the max number of clicks?
clicks = data_float[:,7]
print(clicks)
ad_id = max(clicks)
print(ad_id)

[  1.   2.   0. ...  28. 135. 114.]
421.0


In [ ]:
#how ,many people bought the product after seeing the ad wit most clicks
#is that the maximum number of purchases in this dataset?
data_float[:,10][data_float[:,7]==421]

array([13.])

In [ ]:
  
data_float[:, 10].max()

21.0

In [ ]:
#the ad with the most clicks didnt fectch the maximum number of purchases. find the details of the product having maximun number of purchases
data_float[data_float[:,10]==21]

array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])

In [ ]:
data_float

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])