<a href="https://colab.research.google.com/github/jennadof/assignment/blob/main/miniproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/makeSenseOfCensus.csv")
df.head()

age  education-num  race  sex  capital-gain  capital-loss  hours-per-week  \
0   39             13     4    1          2174             0              40   
1   50             13     4    1             0             0              13   
2   38              9     4    1             0             0              40   
3   53              7     2    1             0             0              40   
4   28             13     2    0             0             0              40   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
data_file ='makeSenseOfCensus.csv'
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [ ]:
 print(type(data))

<class 'numpy.ndarray'>


In [ ]:
new_record = np.array([[50,9,4,1,0,0,40,0]], dtype = "float")
print(new_record)
print(data)

[[50.  9.  4.  1.  0.  0. 40.  0.]]
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [ ]:
data = np.concatenate((data, new_record))
print(data)


[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
age = np.array(data[:,0])
print(age)
max_age = age.max()
print(max_age)
min_age = age.min()
print(min_age)
mean_age = age.mean()
print(round(mean_age))
age_std = age.std()
print(round(age_std))


[39. 50. 38. ... 40. 39. 50.]
90.0
17.0
38
13


In [ ]:
race_0 =data[data[:,2]==0]
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


In [ ]:
race_1 =data[data[:,2]==1]
print(race_1)


[[3.000e+01 1.300e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [4.000e+01 1.100e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [5.400e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 6.000e+01
  1.000e+00]
 [3.000e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 1.573e+03 3.500e+01
  0.000e+00]
 [4.900e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.300e+01 1.300e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.400e+01 1.400e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [6.000e+01 9.000e+00 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.200e+01 9.000e+00 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.700e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 7.500e+01
  1.000e+00]
 [3.900e+01 1.400e+01 1.000e+00 0.000e+00 3.464e+03 0.000e+00 4.0

In [ ]:
race_2 =data[data[:,2]==2]
print(race_2)


[[5.300e+01 7.000e+00 2.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 1.300e+01 2.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.900e+01 5.000e+00 2.000e+00 0.000e+00 0.000e+00 0.000e+00 1.600e+01
  0.000e+00]
 [3.700e+01 1.000e+01 2.000e+00 1.000e+00 0.000e+00 0.000e+00 8.000e+01
  1.000e+00]
 [3.200e+01 1.200e+01 2.000e+00 1.000e+00 0.000e+00 0.000e+00 5.000e+01
  0.000e+00]
 [5.400e+01 9.000e+00 2.000e+00 0.000e+00 0.000e+00 0.000e+00 2.000e+01
  0.000e+00]
 [3.500e+01 5.000e+00 2.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.000e+01 1.000e+01 2.000e+00 1.000e+00 0.000e+00 0.000e+00 4.400e+01
  0.000e+00]
 [2.200e+01 1.000e+01 2.000e+00 1.000e+00 0.000e+00 0.000e+00 1.500e+01
  0.000e+00]
 [5.700e+01 1.300e+01 2.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.100e+01 1.300e+01 2.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 1.000e+01 2.000e+00 0.000e+00 0.000e+00 0.000e+00 2.5

In [ ]:
race_3 =data[data[:,2]==3]
print(race_3)

[[2.500e+01 1.000e+01 3.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [3.300e+01 1.000e+01 3.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [6.500e+01 7.000e+00 3.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 4.000e+00 3.000e+00 1.000e+00 0.000e+00 2.179e+03 4.000e+01
  0.000e+00]
 [4.400e+01 7.000e+00 3.000e+00 0.000e+00 0.000e+00 0.000e+00 4.600e+01
  0.000e+00]
 [4.000e+01 1.300e+01 3.000e+00 0.000e+00 0.000e+00 0.000e+00 5.500e+01
  1.000e+00]]


In [ ]:
race_4 =data[data[:,2]==4]
print(race_4)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
len_0=len(race_0)
len_0

10

In [ ]:
len_1=len(race_1)
len_1

27

In [ ]:
len_2=len(race_2)
len_2

110

In [ ]:
len_3=len(race_3)
len_3

6

In [ ]:
len_4=len(race_4)
len_4

848

In [ ]:
minority_race = len(race_0)
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


Step 4: create a list that contains the lengths of all the races(len_1,len_2,...)
Then find the min value in that list using list functions and finally store the index position of that value in variable called minority_race.

In [ ]:
races = [len_1,len_2]


In [ ]:
abc = [10,20,30,40,500]
minority = abc.index(min(abc))
minority

0

In [ ]:
races = [10, 27, 110, 6, 848]
minority = races.index(min(races))
minority

3

STEP 5

In [ ]:
age_df = data[:,0]  #age column


senior_citizens = age_df[age_df > 60] #masking
senior_citizens


array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [ ]:
senior_working = data[:, 6]
print(senior_working)
working_hours_sum = sum(senior_working[age_df>60])
print(working_hours_sum)
                        

[40. 13. 40. ... 40. 50. 40.]
1917.0


In [ ]:
len(senior_working[age_df>60])

61

In [ ]:
avg_working_hours = ((working_hours_sum) / (senior_working[age_df>60]))
print(avg_working_hours)

[ 95.85       958.5         47.925       47.925       47.925
  47.925      958.5         95.85        95.85        47.925
  47.925       38.34        95.85        47.925       47.925
  47.925      119.8125      47.925       79.875      191.7
  42.6         34.85454545 239.625       47.925       47.925
  47.925       79.875       79.875       54.77142857  95.85
  47.925      213.          39.9375      47.925       47.925
  63.9         79.875      127.8        127.8        479.25
  32.49152542  38.34        47.925       95.85        47.925
  42.6         47.925       47.925       79.875      319.5
  39.9375      47.925       47.925      127.8         34.85454545
  47.925       63.9        383.4         47.925       47.925
  95.85      ]


step 6

In [ ]:
education_num = data[:,1]
high = education_num[education_num > 10]
high
low = education_num[education_num <=10]
low

array([ 9.,  7.,  5.,  9., 10.,  4.,  9.,  9.,  7.,  9.,  5.,  7.,  9.,
        9., 10.,  9.,  9., 10., 10., 10.,  7., 10.,  9., 10.,  5.,  9.,
        9.,  9., 10.,  9.,  9., 10.,  3.,  9.,  9.,  4.,  9., 10.,  9.,
       10.,  9., 10., 10., 10., 10., 10.,  9.,  6.,  7.,  4.,  9.,  9.,
        9.,  9.,  9.,  9.,  5., 10., 10.,  9., 10., 10.,  9., 10.,  9.,
        9.,  6.,  7.,  9.,  9.,  9., 10.,  9.,  5., 10., 10.,  9., 10.,
       10., 10.,  9., 10.,  9.,  9.,  9., 10., 10.,  9., 10., 10., 10.,
        9., 10.,  9.,  7., 10., 10.,  9.,  9.,  9.,  9., 10.,  9.,  2.,
        9.,  9., 10.,  7.,  9.,  9., 10.,  9.,  9.,  9.,  9., 10., 10.,
       10.,  4., 10.,  9., 10., 10., 10.,  3., 10.,  9.,  9., 10.,  9.,
        7.,  9.,  9.,  7.,  9.,  9., 10.,  9.,  4.,  6., 10.,  2.,  9.,
        9.,  1.,  9.,  6.,  9.,  9.,  7.,  9., 10., 10.,  9., 10.,  9.,
        9., 10., 10.,  9.,  9.,  9.,  9.,  6., 10., 10.,  9.,  9.,  9.,
        4.,  9.,  7., 10.,  7., 10., 10.,  9.,  9.,  9.,  5.,  9

In [116]:
income = data[:, 7]
print(income)
avg_pay_high =np. mean(income[education_num > 10])
print(avg_pay_high)
avg_pay_low = np.mean(income[education_num <=10])
print(avg_pay_low)



[0. 0. 0. ... 0. 1. 0.]
0.42813455657492355
0.13649851632047477
